import 'package:athena/presentation/theme/prebuilt_themes/base_theme.dart';
import 'package:flutter/material.dart';

/// Colors for Black Swan theme
/// Original color scheme by Anti049
/// M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
///
/// Key colors:
/// Primary #BE8FF6
/// Secondary #99B2F4
/// Tertiary #E96AB8
/// Neutral #3E3550
final silverWolfTheme = BaseTheme.fromColors(
  "silver_wolf",
  ThemeCategory.hsr,
  const Color(0xFFBE8FF6),
  secondary: const Color(0xFF99B2F4),
  tertiary: const Color(0xFFE96AB8),
  neutral: const Color(0xFF3E3550),
);
