package_rename_config:
    android:
        app_name: Athena
        package_name: dev.nploetz.athena
        override_old_package: dev.nploetz049.athena
        lang: kotlin

    ios:
        app_name: Athena
        bundle_name: athena
        package_name: dev.nploetz.athena

    web:
        app_name: Athena
        description: Fanfiction download/reading application.

    linux:
        app_name: Athena
        package_name: dev.nploetz.athena
        exe_name: athena-linux-x64

    windows:
        app_name: Athena
        organization: nploetz
        copyright_notice: Copyright ©️ 2024 nploetz. All rights reserved.
        exe_name: athena-win32

    macos:
        app_name: Athena
        package_name: dev.nploetz.athena
        copyright_notice: Copyright ©️ 2024 nploetz. All rights reserved.
