name: athena

version: '0.1.0'

publish_to: none

environment:
    sdk: '^3.5.2'

description: A new Flutter project.

dependencies:
    animated_visibility: ^0.0.4
    archive: ^4.0.2
    auto_route: '^9.2.2'
    collection: ^1.18.0
    cupertino_icons: ^1.0.8
    dartx: ^1.2.0
    device_info_plus: ^11.2.0
    dynamic_color: ^1.7.0
    file_picker: ^8.1.7
    flex_color_scheme: ^8.0.2
    flex_seed_scheme: ^3.4.1
    flutter:
        sdk: flutter
    flutter_layout_grid: ^2.0.7
    flutter_localized_locales: '^2.0.5'
    flutter_riverpod: '^2.5.1'
    flutter_svg: ^2.0.16
    freezed_annotation: '^2.4.4'
    hive_ce: ^2.8.0+2
    hive_ce_flutter: ^2.1.0
    i69n: '^3.0.0'
    json_annotation: '^4.9.0'
    logger: ^2.5.0
    material_symbols_icons: ^4.2800.2
    path_provider: '^2.1.4'
    permission_handler: ^11.3.1
    responsive_framework: ^1.5.1
    riverpod_annotation: '^2.3.5'
    rxdart: ^0.28.0
    side_sheet: ^1.0.4
    stream_transform: ^2.1.1
    system_theme: ^3.1.2
    xml: ^6.5.0

dev_dependencies:
    auto_route_generator: '^9.0.0'
    build_runner: '^2.4.13'
    custom_lint: '^0.6.7'
    flutter_lints: '^4.0.0'
    flutter_test:
        sdk: flutter
    freezed: '^2.5.7'
    hive_ce_generator: ^1.8.1
    json_serializable: '^6.8.0'
    riverpod_generator: '^2.4.3'
    riverpod_lint: '^2.3.13'

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/icons/
        - assets/images/
        - assets/themes/
