name: athena
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.5.2

dependencies:
    animated_visibility: ^0.0.4
    animations: ^2.0.11
    auto_route: ^9.2.2
    change_case: ^2.1.0
    collection: ^1.18.0
    cupertino_icons: ^1.0.8
    dartx: ^1.2.0
    dynamic_color: ^1.7.0
    easy_localization: ^3.0.7
    easy_localization_loader: ^2.0.2
    flex_color_picker: ^3.6.0
    flex_seed_scheme: ^3.4.1
    flutter:
        sdk: flutter
    flutter_layout_grid: ^2.0.7
    flutter_local_notifications: ^17.2.3
    flutter_localizations:
        sdk: flutter
    flutter_riverpod: ^2.5.1
    flutter_svg: ^2.0.10+1
    freezed_annotation: ^2.4.4
    go_router: ^14.3.0
    google_fonts: ^6.2.1
    grayscale: ^0.0.5+7
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    i69n: ^3.0.0
    intl: ^0.19.0
    json_annotation: ^4.9.0
    material_symbols_icons: ^4.2785.1
    page_transition: ^2.1.0
    path_provider: ^2.1.4
    responsive_framework: ^1.5.1
    riverpod_annotation: ^2.3.5

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    riverpod_generator: ^2.4.3
    build_runner: ^2.4.12
    custom_lint: ^0.6.7
    riverpod_lint: ^2.3.13
    hive_generator: ^2.0.1
    freezed: ^2.5.7
    json_serializable: ^6.8.0
    package_rename: ^1.7.1
    flutter_launcher_icons: ^0.14.1
    auto_route_generator: ^9.0.0

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/images/
