import 'package:athena/features/theme/domain/base_theme.dart';
import 'package:flutter/material.dart';

/// Colors for Green Apple theme
/// Original color scheme by CarlosEsco, Jays2Kings and CrepeTF
/// M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
///
/// Key colors:
/// Primary #188140
/// Secondary #188140
/// Tertiary #D33131
/// Neutral #5D5F5B
final greenAppleTheme = BaseTheme.fromColors(
  'green_apple',
  ThemeCategory.tachiyomi,
  const Color(0xFF188140),
  secondary: const Color(0xFF188140),
  tertiary: const Color(0xFFD33131),
  neutral: const Color(0xFF5D5F5B),
);
