import 'package:athena/features/theme/domain/base_theme.dart';
import 'package:flex_seed_scheme/flex_seed_scheme.dart';
import 'package:flutter/material.dart';

/// Colors for Gaziter theme
/// Original color scheme by nploetz049
/// Inspired by Gaziter (https://x.com/Gaziter/status/1668548308963344384/photo/1)
/// M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
///
/// Key colors:
/// Primary #48F7BD
/// Secondary #C193FF
/// Tertiary #54A5B6
/// Error #FF5555
/// Neutral #04485F
final gaziterTheme = BaseTheme.fromColors(
  'gaziter',
  ThemeCategory.custom,
  const Color(0xFF48F7BD),
  secondary: const Color(0xFFC193FF),
  tertiary: const Color(0xFF54A5B6),
  error: const Color(0xFFFF5555),
  neutral: const Color(0xFF04485F),
  variant: FlexSchemeVariant.vibrant,
);
