import 'package:athena/features/theme/domain/base_theme.dart';
import 'package:flutter/material.dart';

/// Colors for Midnight Dusk theme
/// Original color scheme by CrepeTF
/// M3 color scheme generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
///
/// Key colors:
/// Primary #F02475
/// Secondary #F02475
/// Tertiary #7A5733
/// Neutral #16151D
final midnightDuskTheme = BaseTheme.fromColors(
  'midnight_dusk',
  ThemeCategory.tachiyomi,
  const Color(0xFFF02475),
  secondary: const Color(0xFFF02475),
  tertiary: const Color(0xFF7A5733),
  neutral: const Color(0xFF16151D),
);
