import 'package:athena/features/theme/domain/base_theme.dart';
import 'package:flutter/material.dart';

/// Colors for Yotsuba theme
/// Original color scheme by ztimms73
/// M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
///
/// Key colors:
/// Primary 0xFFAE3200
/// Secondary 0xFFAE3200
/// Tertiary 0xFF6B5E2F
/// Neutral 0xFF655C5A
final yotsubaTheme = BaseTheme.fromColors(
  'yotsuba',
  ThemeCategory.tachiyomi,
  const Color(0xFFAE3200),
  secondary: const Color(0xFFAE3200),
  tertiary: const Color(0xFF6B5E2F),
  neutral: const Color(0xFF655C5A),
);
