import 'package:athena/features/theme/models/base_theme.dart';
import 'package:flutter/material.dart';

/// Colors for Tako theme
/// Original color scheme by ghostbear
/// M3 color scheme generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
///
/// Key colors:
/// Primary #F3B375
/// Secondary #F3B375
/// Tertiary #66577E
/// Neutral #21212E
final takoTheme = BaseTheme.fromColors(
  'tako',
  ThemeCategory.tachiyomi,
  const Color(0xFFF3B375),
  secondary: const Color(0xFFF3B375),
  tertiary: const Color(0xFF66577E),
  neutral: const Color(0xFF21212E),
);
