import 'package:athena/features/theme/models/base_theme.dart';
import 'package:flutter/material.dart';

/// Colors for Strawberry Daiquiri theme
/// Original color scheme by Soitora
/// M3 color scheme generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
///
/// Key colors:
/// Primary #ED4A65
/// Secondary #ED4A65
/// Tertiary #775930
/// Neutral #655C5C
final strawberryTheme = BaseTheme.fromColors(
  'strawberry',
  ThemeCategory.tachiyomi,
  const Color(0xFFED4A65),
  secondary: const Color(0xFFED4A65),
  tertiary: const Color(0xFF775930),
  neutral: const Color(0xFF655C5C),
);
