name: Build & Release

# Run when a new version tag is pushed (v0.1.0 -> v0.1.1)
on: 
    push:
        branches:
            - main
        tags:
            - 'v*.*.*'
    workflow_dispatch:

jobs:
    build-android:
        name: Build Android
        runs-on: ubuntu-latest
        steps:
            # Step 0.1: Get Repository Name
            - name: Get Repository Name
              id: get_repo_name
              run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

            # Step 0.2: Get Version from Tag
            - name: Get Version from Tag
              id: get_version
              run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

            # Step 1: Checkout Repository
            - name: Checkout code
              uses: actions/checkout@v4

            # Step 2: Setup Flutter
            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable

            # Step 2.5: Setup Java
            - name: Setup Java
              uses: actions/setup-java@v4.5.0
              with:
                distribution: 'oracle'
                java-version: '21'

            # Step 3: Verify Flutter
            - name: Verify Flutter
              run: |
                  flutter --version
                  flutter doctor --verbose

            # Step 3.5: Disable Analytics
            - name: Disable Analytics
              run: flutter config --no-analytics

            # Step 4: Install Dependencies
            - name: Install Dependencies
              run: flutter pub get

            # Step 4.5: Generate Intermediates
            - name: Generate Intermediates
              run: dart run build_runner build --delete-conflicting-outputs

            # Step 5: Run Tests
            - name: Run Tests
              run: flutter analyze

            # Step 6.1: Build App Bundle
            - name: Build App Bundle
              run: flutter build appbundle --flavor production -t lib/main_production.dart --release

            # Step 6.2: Build APK
            - name: Build APK
              run: flutter build apk --flavor production -t lib/main_production.dart --release

            # Step 7: Rename APK and AAB Files
            - name: Rename APK and AAB Files
              run: |
                  mv build/app/outputs/bundle/**/*.aab build/app/outputs/bundle/$REPO_NAME-$VERSION.aab
                  mv build/app/outputs/flutter-apk/*.apk build/app/outputs/flutter-apk/$REPO_NAME-$VERSION.apk

            # Step 8.1: Upload AAB File
            - name: Upload AAB File
              uses: actions/upload-artifact@v4
              with:
                  name: $REPO_NAME-$VERSION-aab
                  path: build/app/outputs/bundle/$REPO_NAME-$VERSION.aab

            # Step 8.2: Upload APK File
            - name: Upload APK File
              uses: actions/upload-artifact@v4
              with:
                  name: $REPO_NAME-$VERSION-apk
                  path: build/app/outputs/flutter-apk/$REPO_NAME-$VERSION.apk

    build-ios:
        name: Build iOS
        runs-on: macos-latest
        steps:
            # Step 0.1: Get Repository Name
            - name: Get Repository Name
              id: get_repo_name
              run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

            # Step 0.2: Get Version from Tag
            - name: Get Version from Tag
              id: get_version
              run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

            # Step 1: Checkout Repository
            - name: Checkout code
              uses: actions/checkout@v4

            # Step 2: Setup Flutter
            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable

            # Step 3: Verify Flutter
            - name: Verify Flutter
              run: |
                  flutter --version
                  flutter doctor --verbose

            # Step 3.5: Disable Analytics
            - name: Disable Analytics
              run: flutter config --no-analytics

            # Step 4: Install Dependencies
            - name: Install Dependencies
              run: flutter pub get

            # Step 4.5: Generate Intermediates
            - name: Generate Intermediates
              run: dart run build_runner build --delete-conflicting-outputs

            # Step 5: Run Tests
            - name: Run Tests
              run: flutter analyze

            # Step 6: Build iOS
            - name: Build iOS
              run: flutter build ios --flavor production -t lib/main_production.dart --release --no-codesign

            # Step 7: Compress Archives and IPAs
            - name: Compress Archives and IPAs
              run: |
                  cd build
                  tar -czf $REPO_NAME-$VERSION-ios.tar.gz ios

            # Step 8: Upload Archives and IPAs
            - name: Upload Archives and IPAs
              uses: actions/upload-artifact@v4
              with:
                  name: $REPO_NAME-$VERSION-ios
                  path: build/$REPO_NAME-$VERSION-ios.tar.gz

    release:
        name: Release
        runs-on: ubuntu-latest
        needs: [build-android, build-ios]
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            # Step 0.1: Get Repository Name
            - name: Get Repository Name
              id: get_repo_name
              run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

            # Step 0.2: Get Version from Tag
            - name: Get Version from Tag
              id: get_version
              run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

            # Step 1.1: Download AAB Artifact (Android)
            - name: Download AAB Artifact
              uses: actions/download-artifact@v4
              with:
                  name: ${{ needs.build-android.outputs.REPO_NAME }}-${{ needs.build-android.outputs.VERSION }}-aab

            # Step 1.2: Download APK Artifact (Android)
            - name: Download APK Artifact
              uses: actions/download-artifact@v4
              with:
                  name: ${{ needs.build-android.outputs.REPO_NAME }}-${{ needs.build-android.outputs.VERSION }}-apk

            # Step 1.3: Download Artifacts (iOS)
            - name: Download Artifacts (iOS)
              uses: actions/download-artifact@v4
              with:
                  name: ${{ needs.build-ios.outputs.REPO_NAME }}-${{ needs.build-ios.outputs.VERSION }}-ios
              
            # Step 2: Create Release
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                artifacts: |
                  ${{ needs.build-android.outputs.REPO_NAME }}-${{ needs.build-android.outputs.VERSION }}-aab
                  ${{ needs.build-android.outputs.REPO_NAME }}-${{ needs.build-android.outputs.VERSION }}-apk
                  ${{ needs.build-ios.outputs.REPO_NAME }}-${{ needs.build-ios.outputs.VERSION }}-ios
                tag: v${{ env.VERSION }}
                token: ${{ secrets.TOKEN }}