name: Build macOS (Development)

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: macOS Build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      # Gather Info
      - name: Check Shell
        run: echo $SHELL

      - name: Check Number of Cores
        run: sysctl -n hw.ncpu

      - name: Check Directory
        run: echo $(pwd)

      - name: Check OS Version
        run: sw_vers

      - name: Check Architecture
        run: uname -a

      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      # Main Dependencies
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'

      - name: Verify Flutter
        run: |
          flutter --version
          flutter doctor --verbose

      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      - name: Install Dependencies
        run: flutter pub get

      # Testing
      - name: Run Tests
        # run: |
        #   dart fix --dry-run
        #   dart test shared/test --reporter github --concurrency=4 --chain-stack-traces
        run: dart fix --dry-run

      # Build
      - name: Build macOS
        run: flutter build macos --flavor development --release --no-codesign

      # Release
      - name: Extract Version
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Check if Tag Exists
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Modify Tag
        if: env.TAG_EXISTS == 'true'
        id: modify_tag
        run: |
          new_version="${{ env.VERSION }}-build-${{ github.run_number }}"
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/macos/Build/Products/Release/*.app
          tag: v${{ env.VERSION }}
          token: ${{ secrets.TOKEN }}